spring.application.name=StudentChatbot
spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:57970/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=EWrHrPkMCbzQKvcTqhGSfzpOKSyegpgg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings

spring.main.allow-circular-references=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.devtools.restart.enabled=false
gemini.api.key=AIzaSyA_daUe6ngbBs4nGK_awgwcGa0_2Qnx0SQ
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB